CREATE schema onlineshop;

use onlineshop;

CREATE TABLE USER (ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
EMAIL VARCHAR (40) UNIQUE,
PASSWORD VARCHAR(30),
FIRST_NAME VARCHAR (30),
LAST_NAME VARCHAR (30),
ADDRESS VARCHAR (50),
PHONE_NUMBER CHAR(13),
DISCOUNT DECIMAL (4,2),
STATUS VARCHAR(20));

CREATE TABLE PRODUCT (ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NAME VARCHAR (255),
PRICE DECIMAL(5,2),
DISCOUNT DECIMAL (2,2),
CATEGORY ENUM('CLOTHES',  'TOYS', 'HYGIENE'),
SUBCATEGORY ENUM('GIRLS', 'BOYS', 'NEWBORN', 'UNDERWEAR'),
IMAGE VARCHAR (255),
MANUFACTURER VARCHAR (255),
MATERIAL VARCHAR (255));

CREATE TABLE PRODUCT_SIZE (ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_ID INT NOT NULL ,
SIZE INT,
QUANTITY INT);

CREATE TABLE `ORDER` (ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
USER_ID INT NOT NULL,
TOTAL_PRICE DECIMAL (10,2),
STATUS ENUM ('NEW', 'IS_FORMED', 'SENT', 'DELIVERED'),
ORDER_DATE DATE NULL);

CREATE TABLE ITEM (ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_ID INT NOT NULL,
PRODUCT_SIZE INT,
ORDER_ID INT NOT NULL,
QUANTITY INT,
DISCOUNT DECIMAL (4,2));

ALTER TABLE ITEM ADD CONSTRAINT PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE;
ALTER TABLE ITEM ADD CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID) ON DELETE CASCADE;
ALTER TABLE `ORDER` ADD CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USER(ID);
ALTER TABLE PRODUCT_SIZE ADD CONSTRAINT PRODUCT_KEY FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID);

SELECT * FROM PRODUCT WHERE SUBCATEGORY = 'GIRLS';


INSERT INTO PRODUCT (NAME, PRICE, DISCOUNT, CATEGORY, SUBCATEGORY, IMAGE) VALUE
('майка',	7,	0.0,	'CLOTHES',	'UNDERWEAR', ''),
('майка белая', 4.25,	0.0,	'CLOTHES', 'UNDERWEAR', ''),
('комплект',	9.99,	0.0,	'CLOTHES',	'UNDERWEAR', 'image/1.jpg'),
('майка для девочки',	4.5,	0.3,	'CLOTHES',	'UNDERWEAR', ''),
('майка для мальчика',	5,	0.3,	'CLOTHES',	'UNDERWEAR', '');
